### ISSUE TITLE
combinators.constant without name crashes

### ISSUE THREAD

**Issue by daddinuz** [fcracker79/pycomb#1]
```python
Nature = combinators.union(combinators.constant('natural'), combinators.constant('artificial'))
```
the code above will produce the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pycomb/combinators.py", line 121, in _struct
    new_dict[k] = combinators[k](x.get(k), ctx=new_ctx)
  File "/usr/local/lib/python3.5/site-packages/pycomb/combinators.py", line 180, in _union
    expected=' or '.join(map(lambda d: get_type_name(d), combinators)), found_type=type(x))
TypeError: sequence item 0: expected str instance, NoneType found
```

The code below instead works fine:
```python
Nature = combinators.union(combinators.constant('natural', name='natural'), combinators.constant('artificial', name='artificial'), name='Nature')
```

**Comment by fcracker79** [comment]
Fixed in release 0.1.8.
Commit: [e35445e28047691cfd7244aedb885abe691a5b20](https://github.com/fcracker79/pycomb/commit/e35445e28047691cfd7244aedb885abe691a5b20)
